"""
Test suite for StrategyConfigManager (Phase 1 configuration system).

Tests:
  1. Loading strategy_config.json (generated by edge_discovery)
  2. Accessing per-symbol strategies
  3. Getting strategy parameters
  4. Validation and hot-reload
  5. Backward compatibility with focused_rules()
  6. Data-driven generation from edge_discovery sweep
"""

import pytest
import json
import os
import tempfile
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock

from src.learning.strategy_config_manager import (
    StrategyConfigManager,
    initialize,
    get_manager,
)
from src.learning import edge_weights
from src.learning.edge_discovery import EdgeDiscovery, _strategy_config_path


class TestStrategyConfigGeneration:
    """Test generation of strategy_config.json from edge_discovery."""
    
    def test_edge_discovery_generates_strategy_config(self):
        """Test that edge_discovery.sweep_all() generates strategy_config.json."""
        # This requires a real registry and backtester, so we use mocking
        # to verify the generation logic works
        
        # Create a mock overlay as if from sweep_all()
        overlay = {
            "edge_weights": {
                "XAUUSD": {"OsMA_Confluence": 1.45}
            },
            "regime_edge": {
                "XAUUSD": {
                    "OsMA_Confluence": {
                        "trending": 1.30,
                        "volatile": 1.15,
                        "ranging": 0.90,
                        "quiet": 0.85
                    }
                }
            },
            "focused_edge": {
                "XAUUSD": [["OsMA_Confluence", ["trending", "volatile"]]]
            },
            "meta": {
                "swept_at": "2026-08-24T10:00:00+00:00",
                "min_pf": 1.15,
                "timeframe": "M15",
                "symbols": {
                    "XAUUSD": {"validated": True, "pockets": 1}
                }
            }
        }
        
        # Create mock registry
        mock_registry = Mock()
        mock_strategy = Mock()
        mock_strategy.params_default = {
            "osma_fast": 12,
            "osma_slow": 26,
            "osma_signal": 9,
            "bulls_min_long": 0.8,
            "bears_min_short": 0.8
        }
        mock_registry._strategies = {"OsMA_Confluence": mock_strategy}
        
        # Create EdgeDiscovery
        mock_bt = Mock()
        ed = EdgeDiscovery(mock_registry, mock_bt, knowledge_store=None)
        
        # Generate strategy_config
        config = ed._generate_strategy_config(overlay)
        
        # Verify structure
        assert config["version"] == "1.0"
        assert "XAUUSD" in config["strategies"]
        assert len(config["strategies"]["XAUUSD"]) >= 1
        
        # Verify first strategy
        first_strategy = config["strategies"]["XAUUSD"][0]
        assert first_strategy["rank"] == 1
        assert first_strategy["strategy"] == "OsMA_Confluence"
        assert first_strategy["enabled"] is True
        assert "parameters" in first_strategy
        assert first_strategy["parameters"]["osma_fast"] == 12
    
    def test_strategy_config_with_no_validated_pocket(self):
        """Test strategy_config generation when no pocket is validated."""
        overlay = {
            "edge_weights": {},
            "regime_edge": {},
            "focused_edge": {
                "GER40": []  # No validated pocket
            },
            "meta": {
                "swept_at": "2026-08-24T10:00:00+00:00",
                "min_pf": 1.15,
                "timeframe": "M15",
                "symbols": {
                    "GER40": {"validated": False, "pockets": 0}
                }
            }
        }
        
        mock_registry = Mock()
        mock_bt = Mock()
        ed = EdgeDiscovery(mock_registry, mock_bt, knowledge_store=None)
        
        config = ed._generate_strategy_config(overlay)
        
        # Should have fallback strategy
        assert "GER40" in config["strategies"]
        strategies = config["strategies"]["GER40"]
        assert len(strategies) >= 1
        
        # First strategy should be OsMA_Confluence (ensemble fallback)
        assert strategies[0]["strategy"] == "OsMA_Confluence"
        assert strategies[0]["enabled"] is True
        assert "no validated focused pocket" in strategies[0]["description"].lower()


class TestStrategyConfigManager:
    """Test StrategyConfigManager core functionality."""
    
    @pytest.fixture
    def generated_config_path(self):
        """Generate a test strategy_config.json."""
        # Create a minimal valid config
        config = {
            "version": "1.0",
            "metadata": {
                "description": "Test config",
                "swept_at": "2026-08-24T10:00:00Z",
                "generated_from": "edge_discovery test"
            },
            "strategies": {
                "XAUUSD": [
                    {
                        "rank": 1,
                        "strategy": "OsMA_Confluence",
                        "enabled": True,
                        "description": "Primary strategy",
                        "parameters": {
                            "osma_fast": 12,
                            "osma_slow": 26,
                            "osma_signal": 9,
                            "bulls_min_long": 0.8,
                            "bears_min_short": 0.8
                        },
                        "performance": {
                            "vectorbt_pf": 1.45,
                            "vectorbt_wr": 0.52,
                            "last_validated": "2026-08-24T10:00:00Z",
                            "validation_bars": 12000,
                            "trades_tested": 156
                        },
                        "optuna_study": None,
                        "notes": "Discovered via edge_discovery sweep"
                    }
                ],
                "BTCUSD": [
                    {
                        "rank": 1,
                        "strategy": "Bollinger_OsMA",
                        "enabled": True,
                        "description": "Primary strategy",
                        "parameters": {
                            "max_extension_atr": 2.0,
                            "ATR_Multiplier": 1.889,
                            "osma_fast": 12,
                            "osma_slow": 26,
                            "osma_signal": 9
                        },
                        "performance": {
                            "vectorbt_pf": 1.18,
                            "vectorbt_wr": 0.59,
                            "last_validated": "2026-08-24T10:00:00Z",
                            "validation_bars": 12000,
                            "trades_tested": 213
                        },
                        "optuna_study": "btcusd_bollinger_osma_v1",
                        "notes": "Generated by edge_discovery"
                    },
                    {
                        "rank": 2,
                        "strategy": "OsMA_Confluence",
                        "enabled": True,
                        "description": "Fallback strategy",
                        "parameters": {
                            "osma_fast": 12,
                            "osma_slow": 26,
                            "osma_signal": 9,
                            "bulls_min_long": 0.8,
                            "bears_min_short": 0.8
                        },
                        "performance": {
                            "vectorbt_pf": 1.08,
                            "vectorbt_wr": 0.50,
                            "last_validated": "2026-08-24T10:00:00Z",
                            "validation_bars": 12000,
                            "trades_tested": 187
                        },
                        "optuna_study": None,
                        "notes": "Fallback if primary holds"
                    }
                ]
            },
            "defaults": {
                "fallback_on_hold": True,
                "description": "If primary strategy returns HOLD, try next-ranked strategy for same symbol"
            }
        }
        
        # Write to temp file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(config, f)
            temp_path = f.name
        
        yield temp_path
        
        # Cleanup
        try:
            os.unlink(temp_path)
        except:
            pass
    
    def test_load_config(self, generated_config_path):
        """Test loading generated strategy_config.json."""
        manager = StrategyConfigManager(generated_config_path)
        summary = manager.get_config_summary()
        
        assert summary["num_symbols"] == 2, "Should have 2 symbols"
        assert "XAUUSD" in summary["symbols"], "XAUUSD should be in symbols"
        assert "BTCUSD" in summary["symbols"], "BTCUSD should be in symbols"
    
    def test_validate_config(self, generated_config_path):
        """Test configuration validation."""
        manager = StrategyConfigManager(generated_config_path)
        is_valid, errors = manager.validate_config()
        
        assert is_valid, f"Configuration validation failed: {errors}"
    
    def test_get_ranked_strategies_xauusd(self, generated_config_path):
        """Test getting ranked strategies for XAUUSD."""
        manager = StrategyConfigManager(generated_config_path)
        strategies = manager.get_ranked_strategies("XAUUSD")
        
        assert strategies is not None, "No strategies for XAUUSD"
        assert len(strategies) >= 1, "XAUUSD has no strategies"
        
        # First should be OsMA_Confluence (rank 1)
        strategy_name, _ = strategies[0]
        assert strategy_name == "OsMA_Confluence", f"First strategy should be OsMA_Confluence, got {strategy_name}"
    
    def test_get_ranked_strategies_btcusd(self, generated_config_path):
        """Test getting ranked strategies for BTCUSD."""
        manager = StrategyConfigManager(generated_config_path)
        strategies = manager.get_ranked_strategies("BTCUSD")
        
        assert strategies is not None, "No strategies for BTCUSD"
        assert len(strategies) >= 2, "BTCUSD should have fallback strategies"
    
    def test_get_strategy_parameters(self, generated_config_path):
        """Test getting parameters for a strategy."""
        manager = StrategyConfigManager(generated_config_path)
        
        params = manager.get_strategy_parameters("XAUUSD", "OsMA_Confluence")
        assert params is not None, "No parameters for OsMA_Confluence"
        
        # Check for expected parameters
        assert "osma_fast" in params, "osma_fast not in parameters"
        assert "osma_slow" in params, "osma_slow not in parameters"
        assert params["osma_fast"] == 12, "osma_fast should be 12"
    
    def test_get_strategy_info(self, generated_config_path):
        """Test getting full strategy info including performance."""
        manager = StrategyConfigManager(generated_config_path)
        
        info = manager.get_strategy_info("XAUUSD", "OsMA_Confluence")
        assert info is not None, "No info for OsMA_Confluence"
        
        # Check structure
        assert info["rank"] == 1, "Expected rank 1"
        assert info["strategy"] == "OsMA_Confluence"
        assert "performance" in info, "Missing performance metrics"
        assert "vectorbt_pf" in info["performance"], "Missing PF metric"
    
    def test_get_all_symbols(self, generated_config_path):
        """Test getting all configured symbols."""
        manager = StrategyConfigManager(generated_config_path)
        symbols = manager.get_all_symbols()
        
        assert "XAUUSD" in symbols, "XAUUSD not in symbols list"
        assert "BTCUSD" in symbols, "BTCUSD not in symbols list"
    
    def test_get_defaults(self, generated_config_path):
        """Test getting default settings."""
        manager = StrategyConfigManager(generated_config_path)
        defaults = manager.get_defaults()
        
        assert "fallback_on_hold" in defaults, "Missing fallback_on_hold setting"
        assert defaults["fallback_on_hold"] is True
    
    def test_case_insensitive_symbol_lookup(self, generated_config_path):
        """Test that symbol lookup is case-insensitive."""
        manager = StrategyConfigManager(generated_config_path)
        
        # These should all return the same result
        strats_upper = manager.get_ranked_strategies("XAUUSD")
        strats_lower = manager.get_ranked_strategies("xauusd")
        strats_mixed = manager.get_ranked_strategies("XauUsd")
        
        assert strats_upper is not None
        assert len(strats_upper) == len(strats_lower)
        assert len(strats_upper) == len(strats_mixed)
    
    def test_reload(self, generated_config_path):
        """Test hot-reload functionality."""
        manager = StrategyConfigManager(generated_config_path)
        
        # Get initial summary
        summary1 = manager.get_config_summary()
        num_symbols_1 = summary1["num_symbols"]
        
        # Reload
        result = manager.reload()
        assert result is True, "Reload should succeed"
        
        # Verify still works
        summary2 = manager.get_config_summary()
        assert summary2["num_symbols"] == num_symbols_1, "Symbol count changed after reload"
    
    def test_nonexistent_symbol(self, generated_config_path):
        """Test behavior for non-existent symbols."""
        manager = StrategyConfigManager(generated_config_path)
        
        strategies = manager.get_ranked_strategies("NOTREAL")
        assert strategies is None, "Should return None for unknown symbol"


class TestBackwardCompatibility:
    """Test backward compatibility with edge_weights.focused_rules()."""
    
    def test_focused_rules_v2_xauusd(self):
        """Test focused_rules_v2 for XAUUSD."""
        rules = edge_weights.focused_rules_v2("XAUUSD")
        
        assert rules is not None, "focused_rules_v2 returned None"
        assert len(rules) >= 1, "XAUUSD has no strategies"
        
        # Each rule is (strategy_name, allowed_regimes_set)
        for strategy, regimes in rules:
            assert isinstance(strategy, str), "Strategy name should be string"
            assert isinstance(regimes, set), "Regimes should be set"
    
    def test_focused_rules_v2_btcusd(self):
        """Test focused_rules_v2 for BTCUSD."""
        rules = edge_weights.focused_rules_v2("BTCUSD")
        
        assert rules is not None, "focused_rules_v2 returned None for BTCUSD"
        assert len(rules) >= 1, "BTCUSD has no strategies"
    
    def test_focused_rules_fallback(self):
        """Test that focused_rules_v2 falls back to original for unknown symbols."""
        # If config doesn't have this symbol, should fall back to hardcoded
        rules = edge_weights.focused_rules_v2("UNKNOWN_SYMBOL")
        # Should either return None or fallback rules
        # This just ensures it doesn't crash


class TestHotReload:
    """Test hot-reload and runtime configuration updates."""
    
    def test_reload_strategy_config(self):
        """Test reloading strategy config at runtime."""
        # Just verify the function exists and doesn't crash
        # (it will fail if no config file exists, which is expected)
        result = edge_weights.reload_strategy_config()
        # Result can be True, False, or None - just ensure no exception
        assert result is not Exception, "reload_strategy_config should not raise"



if __name__ == "__main__":
    pytest.main([__file__, "-v"])
