"""
Base strategy class for the XAUUSD trading bot.
All trading strategies should inherit from this base class.
"""

from abc import ABC, abstractmethod
from typing import Optional
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        action: "buy", "sell", or "hold".
        symbol: Trading symbol (default: XAUUSD).
        confidence: Signal confidence 0.0-1.0.
        price: Current price when signal was generated.
        stop_loss: Recommended stop loss price.
        take_profit: Recommended take profit price.
        reason: Explanation of why this signal was generated.
        timestamp: When the signal was generated.
        metadata: Additional strategy-specific data.
    """
    action: str  # "buy", "sell", "hold"
    symbol: str = "XAUUSD"
    confidence: float = 0.0
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict = field(default_factory=dict)
    
    def is_valid(self) -> bool:
        """Check if the signal is valid (has required fields)."""
        if self.action == "hold":
            return True
        return (
            self.action in ("buy", "sell")
            and self.price is not None
            and self.confidence > 0.3
        )


@dataclass
class StrategyMetrics:
    """
    Performance metrics for a trading strategy.
    
    Attributes:
        total_trades: Number of trades taken.
        winning_trades: Number of profitable trades.
        losing_trades: Number of losing trades.
        win_rate: Percentage of winning trades.
        profit_factor: Gross profit / gross loss.
        total_profit: Net profit in account currency.
        max_drawdown: Maximum peak-to-trough drawdown.
        sharpe_ratio: Risk-adjusted return metric.
        avg_holding_period: Average trade duration.
    """
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    total_profit: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float = 0.0
    avg_holding_period: float = 0.0


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.
    
    Subclasses must implement:
    - calculate_indicators()
    - generate_signals()
    """
    
    def __init__(self, name: str, params: dict = None):
        """
        Initialize the strategy.
        
        Args:
            name: Strategy name.
            params: Strategy parameters dict.
        """
        self.name = name
        self.params = params or {}
        self.metrics = StrategyMetrics()
    
    @abstractmethod
    def calculate_indicators(self, data: list[dict]) -> dict:
        """
        Calculate technical indicators from market data.
        
        Args:
            data: List of OHLCV candle dicts.
        
        Returns:
            Dict of indicator values.
        """
        pass
    
    @abstractmethod
    def generate_signals(self, data: list[dict]) -> Signal:
        """
        Generate trading signals based on market data.
        
        Args:
            data: List of OHLCV candle dicts.
        
        Returns:
            Signal object with trading decision.
        """
        pass
    
    def validate_signal(self, signal: Signal) -> bool:
        """
        Validate a trading signal before execution.
        
        Args:
            signal: The signal to validate.
        
        Returns:
            True if the signal passes validation.
        """
        if not signal.is_valid():
            return False
        
        # Check for minimum confidence
        if signal.confidence < 0.4:
            return False
        
        return True
    
    def update_metrics(self, trade_result: dict):
        """Update strategy metrics with a trade result."""
        self.metrics.total_trades += 1
        
        profit = trade_result.get("profit", 0)
        if profit > 0:
            self.metrics.winning_trades += 1
        elif profit < 0:
            self.metrics.losing_trades += 1
        
        self.metrics.total_profit += profit
        
        if self.metrics.total_trades > 0:
            self.metrics.win_rate = (
                self.metrics.winning_trades / self.metrics.total_trades * 100
            )
