//+------------------------------------------------------------------+
//|  GoldShark_BTCUSD.mq5                                             |
//|  Auto-generated by QMMP onboarding pipeline (#57/#61)            |
//|  Symbol: BTCUSD   Validated timeframe: H1                       |
//|  Onboarded: 2026-08-18   CONFIG VERSION: 6e67c16aad0f   BUILD: 19  |
//|  Entry: OsMA zero-cross + per-session floors                     |
//|  Exit : single basket trailing stop + early-only pyramiding      |
//|  MT5 forward-test: pipeline validated on 70/30; MT5 optimiser    |
//|    defaults 1/4=25%, 1/3=33%, 1/2=50% forward are all supported. |
//|  DO NOT hand-edit -- regenerate via scripts.qmmp.ea_generator    |
//|  ---- CONFIG SNAPSHOT (must match model.json; verified by        |
//|       ea_generator.verify_ea at pipeline Stage 11) ----          |
//|   OsMA_Fast = 12
//|   OsMA_Slow = 26
//|   OsMA_Signal = 9
//|   OsmaFloor_Asian = 17.971
//|   EmaAlign_Asian = 5.402
//|   BullsFloor_Asian_Long = 433.075
//|   BearsFloor_Asian_Long = 0.0
//|   BullsFloor_Asian_Short = -184.006
//|   BearsFloor_Asian_Short = 0.0
//|   AtrFloor_Asian = 632.985
//|   OsmaFloor_London = 15.243
//|   EmaAlign_London = 10.259
//|   BullsFloor_London_Long = 374.312
//|   BearsFloor_London_Long = 0.0
//|   BullsFloor_London_Short = -142.521
//|   BearsFloor_London_Short = 0.0
//|   AtrFloor_London = 567.043
//|   OsmaFloor_NewYork = 28.439
//|   EmaAlign_NewYork = 76.329
//|   BullsFloor_NewYork_Long = 626.909
//|   BearsFloor_NewYork_Long = 0.0
//|   BullsFloor_NewYork_Short = -137.729
//|   BearsFloor_NewYork_Short = 0.0
//|   AtrFloor_NewYork = 551.449
//|   HardSL_pts = 5000
//|   BE_pts = 5000
//|   BE_lock_pts = 500
//|   Trail_pts = 5000
//|   Add_pts = 5000
//|   EarlyFrac = 0.15
//|   MaxLegs = 2
//|   GBP_per_001 = 50.0
//|   LotCapPerAccount = 100
//|   Magic = 880011
//|   Backtest window: 2024-09-14 -> 2026-01-13
//|   Forward window : 2026-01-13 -> 2026-08-17  (70/30 split, NOT an MT5 preset)
//|   NOTE: Use ForwardMode=4 in MT5 Strategy Tester with ForwardDate=split_date to match pipeline's 70/30 split
//+------------------------------------------------------------------+
#property copyright "QMMP"
#property version   "1.00"
#property description "GoldShark BTCUSD H1 | build 19 | config 6e67c16aad0f | onboarded 2026-08-18"
#property strict

#define QMMP_CONFIG_VERSION "6e67c16aad0f"
#define QMMP_BUILD         "19"
#define QMMP_SYMBOL         "BTCUSD"
#define QMMP_TIMEFRAME      "H1"

// ===== OPTIMISER-COMPATIBLE INPUTS (ranges in GoldShark_BTCUSD.set) =====

input group "Entry / OsMA"
input int    OsMA_Fast = 12;
input int    OsMA_Slow = 26;
input int    OsMA_Signal = 9;

input group "Per-session strength floors (0 = OFF)"
input double OsmaFloor_Asian = 17.971;
input double EmaAlign_Asian = 5.402;
input double BullsFloor_Asian_Long = 433.075;
input double BearsFloor_Asian_Long = 0.0;
input double BullsFloor_Asian_Short = -184.006;
input double BearsFloor_Asian_Short = 0.0;
input double AtrFloor_Asian = 632.985;
input double OsmaFloor_London = 15.243;
input double EmaAlign_London = 10.259;
input double BullsFloor_London_Long = 374.312;
input double BearsFloor_London_Long = 0.0;
input double BullsFloor_London_Short = -142.521;
input double BearsFloor_London_Short = 0.0;
input double AtrFloor_London = 567.043;
input double OsmaFloor_NewYork = 28.439;
input double EmaAlign_NewYork = 76.329;
input double BullsFloor_NewYork_Long = 626.909;
input double BearsFloor_NewYork_Long = 0.0;
input double BullsFloor_NewYork_Short = -137.729;
input double BearsFloor_NewYork_Short = 0.0;
input double AtrFloor_NewYork = 551.449;

input group "Exit: basket trail + early pyramid"
input int    HardSL_pts = 5000;
input int    BE_pts = 5000;
input int    BE_lock_pts = 500;
input int    Trail_pts = 5000;
input int    Add_pts = 5000;
input double EarlyFrac = 0.15;
input int    MaxLegs = 2;

input group "Money management"
input double GBP_per_001 = 50.0;
input int    LotCapPerAccount = 100;
input int    Magic = 880011;


int      hMACD = INVALID_HANDLE, hATR = INVALID_HANDLE, hEMA = INVALID_HANDLE;
int      hBulls = INVALID_HANDLE, hBears = INVALID_HANDLE;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
int OnInit()
  {
   hMACD = iMACD(_Symbol, PERIOD_H1, OsMA_Fast, OsMA_Slow, OsMA_Signal, PRICE_CLOSE);
   hATR  = iATR(_Symbol, PERIOD_H1, 14);
   hEMA  = iMA(_Symbol, PERIOD_H1, 13, 0, MODE_EMA, PRICE_CLOSE);
   hBulls = iBullsPower(_Symbol, PERIOD_H1, 13);
   hBears = iBearsPower(_Symbol, PERIOD_H1, 13);
   if(hMACD==INVALID_HANDLE || hATR==INVALID_HANDLE || hEMA==INVALID_HANDLE || hBulls==INVALID_HANDLE || hBears==INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
   }
void OnDeinit(const int reason){ IndicatorRelease(hMACD); IndicatorRelease(hATR); IndicatorRelease(hEMA); IndicatorRelease(hBulls); IndicatorRelease(hBears); }

//--- OsMA[i] = MACD main - signal (MT5 iMACD buffer 0 = main = MACD line, buffer 1 = signal)
double OsMA(int shift)
  {
   double m[2], s[2];
   if(CopyBuffer(hMACD,0,shift,1,m)<1 || CopyBuffer(hMACD,1,shift,1,s)<1) return(0);
   return(m[0]-s[0]);
   }
double ATRv(int shift){ double a[1]; if(CopyBuffer(hATR,0,shift,1,a)<1) return(0); return(a[0]); }
double EMAv(int shift){ double e[1]; if(CopyBuffer(hEMA,0,shift,1,e)<1) return(0); return(e[0]); }
double BullsP(int shift){ double v[1]; if(CopyBuffer(hBulls,0,shift,1,v)<1) return(0); return(v[0]); }
double BearsP(int shift){ double v[1]; if(CopyBuffer(hBears,0,shift,1,v)<1) return(0); return(v[0]); }

//--- session (broker/server time assumed ~UTC; adjust if your server offset differs)
string CurSession()
  {
   MqlDateTime dt; TimeToStruct(TimeCurrent(), dt); int h=dt.hour;
   if(h>=12 && h<21) return("NewYork");
   if(h>=7  && h<16) return("London");
   if(h>=0  && h<9 ) return("Asian");
   return("Off");
   }
void SessionFloors(string s, bool isLong, double &osma, double &ema, double &bulls, double &bears, double &atr)
  {
   string side = isLong ? "Long" : "Short";
   if(s=="Asian"){  osma=OsmaFloor_Asian;  ema=EmaAlign_Asian;  bulls=isLong?BullsFloor_Asian_Long:BullsFloor_Asian_Short;  bears=isLong?BearsFloor_Asian_Long:BearsFloor_Asian_Short;  atr=AtrFloor_Asian; }
   else if(s=="London"){ osma=OsmaFloor_London; ema=EmaAlign_London; bulls=isLong?BullsFloor_London_Long:BullsFloor_London_Short; bears=isLong?BearsFloor_London_Long:BearsFloor_London_Short; atr=AtrFloor_London; }
   else { osma=OsmaFloor_NewYork; ema=EmaAlign_NewYork; bulls=isLong?BullsFloor_NewYork_Long:BullsFloor_NewYork_Short; bears=isLong?BearsFloor_NewYork_Long:BearsFloor_NewYork_Short; atr=AtrFloor_NewYork; }
   }

//+------------------------------------------------------------------+
void OnTick()
  {
   // one decision per new bar
   datetime bt[]; if(CopyTime(_Symbol,PERIOD_H1,0,1,bt)<1) return;
   if(bt[0]==lastBarTime) { ManageBasket(); return; }
   lastBarTime = bt[0];
   ManageBasket();

   string sess = CurSession();
   if(sess=="Off") return;

   double o1=OsMA(1), o2=OsMA(2);                    // closed bars
   bool crossUp   = (o2<=0 && o1>0);
   bool crossDown = (o2>=0 && o1<0);
   if(!crossUp && !crossDown) return;

    double fOsma,fEma,fBulls,fBears,fAtr; SessionFloors(sess,crossUp,fOsma,fEma,fBulls,fBears,fAtr);
   double osma_mag = MathAbs(o1);
   double ema_slope = EMAv(1)-EMAv(4);               // slope over 3 bars
   double ema_align = crossUp ? ema_slope : -ema_slope;
    double atr = ATRv(1);
   double bulls_al = crossUp ? BullsP(1) : -BullsP(1);   // aligned power (long wants +bulls)
   double bears_al = crossUp ? BearsP(1) : -BearsP(1);
   // KEEP-floor gates (0 = OFF => always passes; validated floors set the non-zero gate)
   if(fOsma>0 && osma_mag < fOsma) return;
   if(fEma!=0 && ema_align < fEma) return;
   if(fAtr>0 && atr < fAtr) return;
   if(fBulls>0 && bulls_al < fBulls) return;
   if(fBears<0 && bears_al > fBears) return;         // bears floor is negative (deeper = stronger)

   OpenLeg(crossUp);
   }

//--- money-management size: floor(equity/GBP_per_001) x 0.01 total, split across MaxLegs,
//--- margin- and 100-lot-capped. (Broker min lot / step assumed 0.01.)
double PerLegLots()
  {
   double eq = AccountInfoDouble(ACCOUNT_EQUITY);
   int units = (int)MathFloor(eq / GBP_per_001);
   double marginOne=0; if(!OrderCalcMargin(ORDER_TYPE_BUY,_Symbol,0.01,SymbolInfoDouble(_Symbol,SYMBOL_ASK),marginOne)) marginOne=0.94;
   if(marginOne>0) units = (int)MathMin(units, MathFloor(eq/marginOne));
   units = (int)MathMin(units, LotCapPerAccount*100);   // 100 lots = 10000 x 0.01
   double perLeg = (units*0.01)/MaxLegs;
   double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   perLeg = MathFloor(perLeg/step)*step;
   double vmin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   double lots = perLeg<vmin?0.0:perLeg;
   Print("GoldShark PerLegLots: eq=", DoubleToString(eq,2), " units=", IntegerToString(units), " perLeg=", DoubleToString(perLeg,2), " lots=", DoubleToString(lots,2));
   return(lots);
   }

void OpenLeg(bool isLong)
  {
   double lots = PerLegLots(); if(lots<=0) return;
   double price = isLong?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = isLong? price-HardSL_pts*_Point : price+HardSL_pts*_Point;
   MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r);
   r.action=TRADE_ACTION_DEAL; r.symbol=_Symbol; r.volume=lots;
   r.type=isLong?ORDER_TYPE_BUY:ORDER_TYPE_SELL; r.price=price; r.sl=sl;
   r.deviation=50; r.magic=Magic; r.comment="GoldShark_BTCUSD";
   if(!OrderSend(r,res)){ /* order rejected; skip */ }
   // update pyramid tracking
   legCount = legCount + 1;
   lastLegPrice = price;
   }

//--- basket trailing stop (single stop behind best) + early pyramid add
double basketBest=0; bool armed=false; int legCount=0; double lastLegPrice=0;
void ManageBasket()
  {
   if(PositionsTotalSym()==0){ armed=false; basketBest=0; legCount=0; lastLegPrice=0; return; }
   bool isLong = NetLong();
   double px = isLong?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK);
   if(basketBest==0) basketBest=px;
   basketBest = isLong?MathMax(basketBest,px):MathMin(basketBest,px);
   double avgEntry=AvgEntry();
   double profitPts = (isLong?(basketBest-avgEntry):(avgEntry-basketBest))/_Point * PositionsTotalSym();
   // BE lock: once profit hits BE_pts, move SL to entry + BE_lock_pts (lock in minimum)
   if(!armed && profitPts>=BE_pts)
     {
      armed = true;
      double lockSl = isLong ? avgEntry + BE_lock_pts*_Point : avgEntry - BE_lock_pts*_Point;
      ModifyAllSL(lockSl);
     }
   if(armed)
     {
      double newSL = isLong? basketBest-Trail_pts*_Point : basketBest+Trail_pts*_Point;
      ModifyAllSL(newSL);
     }
   // early pyramid: add a leg if price advanced Add_pts beyond last leg and still early
   // (heuristic: within first EarlyFrac of estimated cycle length; fallback to legCount<MaxLegs)
   if(legCount>0 && legCount<MaxLegs)
     {
      double adv=(isLong?(px-lastLegPrice):(lastLegPrice-px))/_Point;
      if(adv>=Add_pts){ OpenLeg(isLong); }
     }
   }
// --- helpers (position accounting for this symbol/magic) ---
int PositionsTotalSym(){ int c=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol) c++; } return(c); }
bool NetLong(){ double v=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol) v+=(PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?1:-1); } return(v>=0); }
double AvgEntry(){ double s=0; int n=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol){ s+=PositionGetDouble(POSITION_PRICE_OPEN); n++; } } return(n>0?s/n:0); }
void ModifyAllSL(double sl){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t>0 && PositionGetString(POSITION_SYMBOL)==_Symbol){ MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r); r.action=TRADE_ACTION_SLTP; r.position=t; r.symbol=_Symbol; r.sl=sl; r.tp=0; if(!OrderSend(r,res)){ /* skip */ } } } }
//+------------------------------------------------------------------+
