//+------------------------------------------------------------------+
//|  GoldShark_BTCUSD.mq5                                             |
//|  Auto-generated by QMMP onboarding pipeline (#57/#61)            |
//|  Symbol: BTCUSD   Validated timeframe: H1                       |
//|  Onboarded: 2026-08-18   CONFIG VERSION: 8c33efe6b4cc   BUILD: 23  |
//|  Entry: OsMA zero-cross + per-session floors                     |
//|  Exit : single basket trailing stop + early-only pyramiding      |
//|  MT5 forward-test: pipeline validated on 70/30; MT5 optimiser    |
//|    defaults 1/4=25%, 1/3=33%, 1/2=50% forward are all supported. |
//|  DO NOT hand-edit -- regenerate via scripts.qmmp.ea_generator    |
//|  ---- CONFIG SNAPSHOT (must match model.json; verified by        |
//|       ea_generator.verify_ea at pipeline Stage 11) ----          |
//|   Magic = 926561
//|   EA_Version = 23
//|   MaxDrawdownPct = 20.0
//|   DailyDrawdownPct = 5.0
//|   MinAccountBalance = 80.0
//|   BrokerGMTOffset = 3
//|   TradeMonday = 1
//|   TradeTuesday = 1
//|   TradeWednesday = 1
//|   TradeThursday = 1
//|   TradeFriday = 1
//|   TradeAsian = 1
//|   TradeLondon = 1
//|   TradeNewYork = 1
//|   AvoidRollover = 1
//|   RolloverBufferMins = 30
//|   OsMA_Fast = 12
//|   OsMA_Slow = 26
//|   OsMA_Signal = 9
//|   OsmaFloor_Asian = 17.971
//|   EmaAlign_Asian = 5.402
//|   BullsFloor_Asian_Long = 433.075
//|   BearsFloor_Asian_Long = 0.0
//|   BullsFloor_Asian_Short = -184.006
//|   BearsFloor_Asian_Short = 0.0
//|   AtrFloor_Asian = 632.985
//|   OsmaFloor_London = 15.243
//|   EmaAlign_London = 10.259
//|   BullsFloor_London_Long = 374.312
//|   BearsFloor_London_Long = 0.0
//|   BullsFloor_London_Short = -142.521
//|   BearsFloor_London_Short = 0.0
//|   AtrFloor_London = 567.043
//|   OsmaFloor_NewYork = 28.439
//|   EmaAlign_NewYork = 76.329
//|   BullsFloor_NewYork_Long = 626.909
//|   BearsFloor_NewYork_Long = 0.0
//|   BullsFloor_NewYork_Short = -137.729
//|   BearsFloor_NewYork_Short = 0.0
//|   AtrFloor_NewYork = 551.449
//|   HardSL_pts = 628348
//|   BE_pts = 11057
//|   BE_lock_pts = 1105
//|   Trail_pts = 11057
//|   Add_pts = 11057
//|   EarlyFrac = 0.15
//|   MaxLegs = 4
//|   GBP_per_001 = 50.0
//|   LotCapPerAccount = 100
//|   LogToCSV = 1
//|   Backtest window: 2024-09-14 -> 2026-01-13
//|   Forward window : 2026-01-13 -> 2026-08-17  (70/30 split, NOT an MT5 preset)
//|   NOTE: Use ForwardMode=4 in MT5 Strategy Tester with ForwardDate=split_date to match pipeline's 70/30 split
//+------------------------------------------------------------------+
#property copyright "QMMP"
#property version   "1.00"
#property description "GoldShark BTCUSD H1 | build 23 | config 8c33efe6b4cc | onboarded 2026-08-18"
#property strict

#define QMMP_CONFIG_VERSION "8c33efe6b4cc"
#define QMMP_BUILD         "23"
#define QMMP_SYMBOL         "BTCUSD"
#define QMMP_TIMEFRAME      "H1"

// ===== OPTIMISER-COMPATIBLE INPUTS (ranges in GoldShark_BTCUSD.set) =====

input group "Core / risk"
input int    Magic = 926561;
input int    EA_Version = 23;
input double MaxDrawdownPct = 20.0;
input double DailyDrawdownPct = 5.0;
input double MinAccountBalance = 80.0;

input group "Session / time"
input int    BrokerGMTOffset = 3;
input int    TradeMonday = 1;
input int    TradeTuesday = 1;
input int    TradeWednesday = 1;
input int    TradeThursday = 1;
input int    TradeFriday = 1;
input int    TradeAsian = 1;
input int    TradeLondon = 1;
input int    TradeNewYork = 1;
input int    AvoidRollover = 1;
input int    RolloverBufferMins = 30;

input group "Entry / OsMA"
input int    OsMA_Fast = 12;
input int    OsMA_Slow = 26;
input int    OsMA_Signal = 9;

input group "Per-session strength floors (0 = OFF)"
input double OsmaFloor_Asian = 17.971;
input double EmaAlign_Asian = 5.402;
input double BullsFloor_Asian_Long = 433.075;
input double BearsFloor_Asian_Long = 0.0;
input double BullsFloor_Asian_Short = -184.006;
input double BearsFloor_Asian_Short = 0.0;
input double AtrFloor_Asian = 632.985;
input double OsmaFloor_London = 15.243;
input double EmaAlign_London = 10.259;
input double BullsFloor_London_Long = 374.312;
input double BearsFloor_London_Long = 0.0;
input double BullsFloor_London_Short = -142.521;
input double BearsFloor_London_Short = 0.0;
input double AtrFloor_London = 567.043;
input double OsmaFloor_NewYork = 28.439;
input double EmaAlign_NewYork = 76.329;
input double BullsFloor_NewYork_Long = 626.909;
input double BearsFloor_NewYork_Long = 0.0;
input double BullsFloor_NewYork_Short = -137.729;
input double BearsFloor_NewYork_Short = 0.0;
input double AtrFloor_NewYork = 551.449;

input group "Exit: basket trail + early pyramid"
input int    HardSL_pts = 628348;
input int    BE_pts = 11057;
input int    BE_lock_pts = 1105;
input int    Trail_pts = 11057;
input int    Add_pts = 11057;
input double EarlyFrac = 0.15;
input int    MaxLegs = 4;

input group "Money management"
input double GBP_per_001 = 50.0;
input int    LotCapPerAccount = 100;

input group "Logging"
input int    LogToCSV = 1;


int      hMACD = INVALID_HANDLE, hATR = INVALID_HANDLE, hEMA = INVALID_HANDLE;
int      hBulls = INVALID_HANDLE, hBears = INVALID_HANDLE;
datetime lastBarTime = 0;

    //+------------------------------------------------------------------+
    int OnInit()
      {
       hMACD = iMACD(_Symbol, PERIOD_H1, OsMA_Fast, OsMA_Slow, OsMA_Signal, PRICE_CLOSE);
       hATR  = iATR(_Symbol, PERIOD_H1, 14);
       hEMA  = iMA(_Symbol, PERIOD_H1, 13, 0, MODE_EMA, PRICE_CLOSE);
       hBulls = iBullsPower(_Symbol, PERIOD_H1, 13);
       hBears = iBearsPower(_Symbol, PERIOD_H1, 13);
       if(hMACD==INVALID_HANDLE || hATR==INVALID_HANDLE || hEMA==INVALID_HANDLE || hBulls==INVALID_HANDLE || hBears==INVALID_HANDLE) return(INIT_FAILED);
       SetModelFileName("qmmp_BTCUSD_model.json");
       EventSetTimer(60);
       return(INIT_SUCCEEDED);
       }

    void OnTimer(const int id) { MaybeReloadModel(); }
    void OnDeinit(const int reason){ IndicatorRelease(hMACD); IndicatorRelease(hATR); IndicatorRelease(hEMA); IndicatorRelease(hBulls); IndicatorRelease(hBears); FlushAndCloseLog(); }

    //--- config reload hook (issue #83): re-read data/qmmp/<SYM>/model.json from MQL5 Files folder on demand.
    // MT5 EAs cannot read arbitrary filesystem paths, so the deployment step must copy model.json into
    // MQL5/Files/qmmp_<SYM>_model.json.  OnTimer(60) checks the file mod-time and updates inputs via
    // global overrides.  Inputs declared at file scope remain the defaults; runtime overrides live in
    // g_override_* globals consumed by the floor/eval/exit helpers below.
    string g_modelFile = "qmmp_BTCUSD_model.json";   // set per symbol in OnInit
    datetime g_modelFileTime = 0;
    // runtime overrides (0 means "use input default")
    double g_ov_osma_fast=0, g_ov_osma_slow=0, g_ov_osma_sig=0;
    double g_ov_hard_sl=0, g_ov_be=0, g_ov_be_lock=0, g_ov_trail=0, g_ov_add=0;
    double g_ov_gbp_per_001=0;

    void SetModelFileName(string fname) { g_modelFile = fname; }

    void MaybeReloadModel()
    {
       string path = g_modelFile;
       datetime mtime = (datetime)FileGetInteger(path, FILE_MODIFY_DATE, false);
       if(mtime == 0 || mtime == g_modelFileTime) return;
       string json = ReadFileText(path);
       if(StringLen(json) == 0) return;
       g_modelFileTime = mtime;
       // naive JSON number extraction for the fields we allow to change live
       g_ov_osma_fast  = JsonDouble(json, ""fast"");
       g_ov_osma_slow  = JsonDouble(json, ""slow"");
       g_ov_osma_sig   = JsonDouble(json, ""signal"");
       g_ov_hard_sl    = JsonDouble(json, ""sl"");
       g_ov_be         = JsonDouble(json, ""be"");
       g_ov_trail      = JsonDouble(json, ""trail"");
       g_ov_add        = JsonDouble(json, ""add"");
       g_ov_gbp_per_001= JsonDouble(json, ""gbp_per_001"");
       Print("[QMMP] Reloaded live model from ", path);
    }

    string ReadFileText(string path)
    {
       int h = FileOpen(path, FILE_READ|FILE_TXT|FILE_COMMON|FILE_SHARE_READ|FILE_SHARE_WRITE);
       if(h < 0) return "";
       string out = "";
       while(!FileIsEnding(h)) out += FileReadString(h) + "
";
       FileClose(h);
       return out;
    }

    double JsonDouble(string json, string key)
    {
       int p = StringFind(json, key);
       if(p < 0) return 0;
       p = StringFind(json, ":", p);
       if(p < 0) return 0;
       int q = StringFind(json, ",", p); if(q < 0) q = StringFind(json, "}", p); if(q < 0) q = StringLen(json);
       string sub = StringSubstr(json, p+1, q-p-1);
       StringReplace(sub, " ", ""); StringReplace(sub, "
", ""); StringReplace(sub, """, "");
       return StringToDouble(sub);
    }

    // runtime helpers that prefer override values
    double RtOsMA_Fast() { return g_ov_osma_fast  > 0 ? g_ov_osma_fast  : OsMA_Fast; }
    double RtOsMA_Slow() { return g_ov_osma_slow  > 0 ? g_ov_osma_slow  : OsMA_Slow; }
    double RtOsMA_Sig()  { return g_ov_osma_sig   > 0 ? g_ov_osma_sig   : OsMA_Signal; }
    double RtHardSL()    { return g_ov_hard_sl    > 0 ? g_ov_hard_sl    : HardSL_pts; }
    double RtBE()        { return g_ov_be         > 0 ? g_ov_be         : BE_pts; }
    double RtBE_Lock()   { return g_ov_be_lock    > 0 ? g_ov_be_lock    : BE_lock_pts; }
    double RtTrail()     { return g_ov_trail      > 0 ? g_ov_trail      : Trail_pts; }
    double RtAdd()       { return g_ov_add        > 0 ? g_ov_add        : Add_pts; }
    double RtGBP()       { return g_ov_gbp_per_001> 0 ? g_ov_gbp_per_001: GBP_per_001; }

//--- OsMA[i] = MACD main - signal (MT5 iMACD buffer 0 = main = MACD line, buffer 1 = signal)
double OsMA(int shift)
  {
   double m[2], s[2];
   if(CopyBuffer(hMACD,0,shift,1,m)<1 || CopyBuffer(hMACD,1,shift,1,s)<1) return(0);
   return(m[0]-s[0]);
   }
double ATRv(int shift){ double a[1]; if(CopyBuffer(hATR,0,shift,1,a)<1) return(0); return(a[0]); }
double EMAv(int shift){ double e[1]; if(CopyBuffer(hEMA,0,shift,1,e)<1) return(0); return(e[0]); }
double BullsP(int shift){ double v[1]; if(CopyBuffer(hBulls,0,shift,1,v)<1) return(0); return(v[0]); }
double BearsP(int shift){ double v[1]; if(CopyBuffer(hBears,0,shift,1,v)<1) return(0); return(v[0]); }

    //--- session (broker/server time converted to GMT using BrokerGMTOffset; keep in sync with src/strategies/sessions.py)
    string CurSession()
      {
       // Precedence: NewYork > London > Asian > Off.
       // Must stay in sync with src/strategies/sessions.py::session_of(hour).
       MqlDateTime dt; TimeToStruct(TimeCurrent(), dt); int h=dt.hour - BrokerGMTOffset;
       if(h<0) h+=24; if(h>=24) h-=24;
       if(h>=12 && h<21) return("NewYork");
       if(h>=7  && h<16) return("London");
       if(h>=0  && h<9 ) return("Asian");
       return("Off");
       }
void SessionFloors(string s, bool isLong, double &osma, double &ema, double &bulls, double &bears, double &atr)
  {
   string side = isLong ? "Long" : "Short";
   if(s=="Asian"){  osma=OsmaFloor_Asian;  ema=EmaAlign_Asian;  bulls=isLong?BullsFloor_Asian_Long:BullsFloor_Asian_Short;  bears=isLong?BearsFloor_Asian_Long:BearsFloor_Asian_Short;  atr=AtrFloor_Asian; }
   else if(s=="London"){ osma=OsmaFloor_London; ema=EmaAlign_London; bulls=isLong?BullsFloor_London_Long:BullsFloor_London_Short; bears=isLong?BearsFloor_London_Long:BearsFloor_London_Short; atr=AtrFloor_London; }
   else { osma=OsmaFloor_NewYork; ema=EmaAlign_NewYork; bulls=isLong?BullsFloor_NewYork_Long:BullsFloor_NewYork_Short; bears=isLong?BearsFloor_NewYork_Long:BearsFloor_NewYork_Short; atr=AtrFloor_NewYork; }
   }

    //+------------------------------------------------------------------+
    void OnTick()
      {
       // one decision per new bar
       datetime bt[]; if(CopyTime(_Symbol,PERIOD_H1,0,1,bt)<1) return;
       if(bt[0]==lastBarTime) { ManageBasket(); return; }
       lastBarTime = bt[0];
       ManageBasket();

       if(!IsTradingAllowed()) return;

       string sess = CurSession();
       if(sess=="Off") return;

       double o1=OsMA(1), o2=OsMA(2);                    // closed bars
       bool crossUp   = (o2<=0 && o1>0);
       bool crossDown = (o2>=0 && o1<0);
       if(!crossUp && !crossDown) return;

        double fOsma,fEma,fBulls,fBears,fAtr; SessionFloors(sess,crossUp,fOsma,fEma,fBulls,fBears,fAtr);
       double osma_mag = MathAbs(o1);
       double ema_slope = EMAv(1)-EMAv(4);               // slope over 3 bars
       double ema_align = crossUp ? ema_slope : -ema_slope;
        double atr = ATRv(1);
       double bulls_al = crossUp ? BullsP(1) : -BullsP(1);   // aligned power (long wants +bulls)
       double bears_al = crossUp ? BearsP(1) : -BearsP(1);
       // KEEP-floor gates (0 = OFF => always passes; validated floors set the non-zero gate)
       if(fOsma>0 && osma_mag < fOsma) return;
       if(fEma!=0 && ema_align < fEma) return;
       if(fAtr>0 && atr < fAtr) return;
       if(fBulls>0 && bulls_al < fBulls) return;
       if(fBears<0 && bears_al > fBears) return;         // bears floor is negative (deeper = stronger)

       OpenLeg(crossUp);
       }

    //--- money-management size: floor(balance/GBP_per_001) x 0.01 total, split across MaxLegs,
    //--- margin- and lot-capped. Uses SYMBOL_VOLUME_MIN/MAX/STEP.
    double PerLegLots()
      {
       double balance = AccountInfoDouble(ACCOUNT_BALANCE);
       int units = (int)MathFloor(balance / RtGBP());
       double marginOne=0; if(!OrderCalcMargin(ORDER_TYPE_BUY,_Symbol,0.01,SymbolInfoDouble(_Symbol,SYMBOL_ASK),marginOne)) marginOne=0.94;
       if(marginOne>0) units = (int)MathMin(units, MathFloor(balance/marginOne));
       units = (int)MathMin(units, LotCapPerAccount*100);   // 100 lots = 10000 x 0.01
       double perLeg = (units*0.01)/MaxLegs;
       double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
       double maxLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
       perLeg = MathFloor(perLeg/step)*step;
       double vmin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
       if(perLeg>maxLot) perLeg=maxLot;
       double lots = perLeg<vmin?0.0:perLeg;
       return(lots);
       }

    void OpenLeg(bool isLong)
      {
       double lots = PerLegLots(); if(lots<=0) return;
       double price = isLong?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID);
       double sl = isLong? price-RtHardSL()*_Point : price+RtHardSL()*_Point;
       int digits=(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS);
       sl = NormalizeDouble(sl,digits);
       MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r);
       r.action=TRADE_ACTION_DEAL; r.symbol=_Symbol; r.volume=lots;
       r.type=isLong?ORDER_TYPE_BUY:ORDER_TYPE_SELL; r.price=price; r.sl=sl;
       r.deviation=50; r.magic=Magic; r.comment="GoldShark_BTCUSD";
       if(!OrderSend(r,res)){ /* order rejected; skip */ }
       else { LogEntry(isLong, price, sl, lots); }
       // update pyramid tracking
       legCount = legCount + 1;
       lastLegPrice = price;
       }

    //--- risk / session guards
    double g_dayStartBalance=0; datetime g_dayStart=0; bool g_dailyLock=false;
    bool IsTradingAllowed()
      {
       if(AccountInfoDouble(ACCOUNT_BALANCE) < MinAccountBalance) return(false);
       double balance = AccountInfoDouble(ACCOUNT_BALANCE);
       double equity  = AccountInfoDouble(ACCOUNT_EQUITY);
       if(equity <= balance * (1.0 - MaxDrawdownPct/100.0)) { CloseAllBasket(); return(false); }
       datetime now = TimeCurrent();
       MqlDateTime dt; TimeToStruct(now, dt);
       if(g_dayStart==0 || dt.day != g_dayStart) { g_dayStart=dt.day; g_dayStartBalance=balance; g_dailyLock=false; }
       double dd = (g_dayStartBalance - equity) / g_dayStartBalance * 100.0;
       if(!g_dailyLock && dd >= DailyDrawdownPct) { g_dailyLock=true; CloseAllBasket(); }
       if(g_dailyLock) return(false);
       int wd = (int)dt.day_of_week;
       if(wd==1 && !TradeMonday) return(false);
       if(wd==2 && !TradeTuesday) return(false);
       if(wd==3 && !TradeWednesday) return(false);
       if(wd==4 && !TradeThursday) return(false);
       if(wd==5 && !TradeFriday) return(false);
       int h = dt.hour - BrokerGMTOffset; if(h<0) h+=24; if(h>=24) h-=24;
       int m = h*60 + dt.min;
       if(AvoidRollover) { int rb = 22*60 - RolloverBufferMins; int re = 23*60 + RolloverBufferMins; if(m>=rb && m<=re) return(false); }
       bool asian = (h>=0 && h<9)  && TradeAsian;
       bool london= (h>=7 && h<16) && TradeLondon;
       bool ny    = (h>=12 && h<21)&& TradeNewYork;
       return(asian || london || ny);
      }

    //--- basket trailing stop (single stop behind best) + early pyramid add
    double basketBest=0; bool armed=false; int legCount=0; double lastLegPrice=0;
    void ManageBasket()
      {
       if(PositionsTotalSym()==0){ armed=false; basketBest=0; legCount=0; lastLegPrice=0; return; }
       bool isLong = NetLong();
       double px = isLong?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK);
       if(basketBest==0) basketBest=px;
       basketBest = isLong?MathMax(basketBest,px):MathMin(basketBest,px);
       double avgEntry=AvgEntry();
       double profitPts = (isLong?(basketBest-avgEntry):(avgEntry-basketBest))/_Point * PositionsTotalSym();
       // BE lock: once profit hits RtBE, move SL to entry + RtBE_Lock (lock in minimum)
       if(!armed && profitPts>=RtBE())
         {
          armed = true;
          double lockSl = isLong ? avgEntry + RtBE_Lock()*_Point : avgEntry - RtBE_Lock()*_Point;
          ModifyAllSL(lockSl);
         }
       if(armed)
         {
          double newSL = isLong? basketBest-RtTrail()*_Point : basketBest+RtTrail()*_Point;
          ModifyAllSL(newSL);
         }
       // early pyramid: add a leg if price advanced RtAdd beyond last leg and still early
       if(legCount>0 && legCount<MaxLegs)
         {
          double adv=(isLong?(px-lastLegPrice):(lastLegPrice-px))/_Point;
          if(adv>=RtAdd()){ OpenLeg(isLong); }
         }
       }

    //--- lightweight CSV lifecycle log
    int    hLog=-1; string logFolder="";
    void EnsureLog()
      {
       if(hLog!=INVALID_HANDLE && hLog>=0) return;
       if(!LogToCSV) return;
       logFolder = "GoldShark_Logs\\";
       if(!FolderCreate(logFolder,FILE_COMMON)) { if(GetLastError()!=ERR_FOLDER_EXISTS) return; }
       string fn = logFolder + _Symbol + "_Lifecycle.csv";
       hLog = FileOpen(fn, FILE_WRITE|FILE_READ|FILE_CSV|FILE_COMMON|FILE_SHARE_READ|FILE_SHARE_WRITE, ',');
       if(hLog!=INVALID_HANDLE && FileSize(hLog)==0)
         FileWrite(hLog,"TradeID","Ticket","Type","EntryTime","EntryPrice","EntrySL","Lots",
                   "OsMA","EMA_Slope","Bulls","Bears","ATR","Session","Status","ExitTime","ExitPrice","ExitReason");
      }
    void LogEntry(bool isLong, double price, double sl, double lots)
      {
       if(!LogToCSV) return; EnsureLog(); if(hLog<0) return;
       MqlDateTime dt; TimeToStruct(TimeCurrent(), dt);
       string id = _Symbol + "_" + IntegerToString(Magic) + "_" + TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES);
       FileWrite(hLog, id, 0, isLong?"LONG":"SHORT", TimeToString(TimeCurrent()), DoubleToString(price, 5),
                 DoubleToString(sl, 5), DoubleToString(lots, 3),
                 DoubleToString(OsMA(1),5), DoubleToString(EMAv(1)-EMAv(4),5),
                 DoubleToString(BullsP(1),5), DoubleToString(BearsP(1),5), DoubleToString(ATRv(1),5),
                 CurSession(), "OPEN", "", "", "");
      }
    void LogClose(string reason)
      {
       if(!LogToCSV) return; EnsureLog(); if(hLog<0) return;
       FileWrite(hLog, _Symbol + "_" + IntegerToString(Magic), 0, "", "", "", "", "", "", "", "", "", "",
                 "", "CLOSED", TimeToString(TimeCurrent()), "", reason);
      }
    void FlushAndCloseLog() { if(hLog>=0){ FileClose(hLog); hLog=-1; } }

    void CloseAllBasket()
      {
       for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t>0 && PositionGetInteger(POSITION_MAGIC)==Magic && PositionGetString(POSITION_SYMBOL)==_Symbol){ MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r); r.action=TRADE_ACTION_DEAL; r.position=t; r.symbol=_Symbol; r.type=(PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY)?ORDER_TYPE_SELL:ORDER_TYPE_BUY; r.volume=PositionGetDouble(POSITION_VOLUME); r.deviation=50; if(!OrderSend(r,res)){ /* skip */ } } }
       LogClose("RISK_HALT");
      }
    // --- helpers (position accounting for this symbol/magic) ---
    int PositionsTotalSym(){ int c=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetInteger(POSITION_MAGIC)==Magic && PositionGetString(POSITION_SYMBOL)==_Symbol) c++; } return(c); }
    bool NetLong(){ double v=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetInteger(POSITION_MAGIC)==Magic && PositionGetString(POSITION_SYMBOL)==_Symbol) v+=(PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?1:-1); } return(v>=0); }
    double AvgEntry(){ double s=0; int n=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetInteger(POSITION_MAGIC)==Magic && PositionGetString(POSITION_SYMBOL)==_Symbol){ s+=PositionGetDouble(POSITION_PRICE_OPEN); n++; } } return(n>0?s/n:0); }
    void ModifyAllSL(double sl){ int digits=(int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS); sl=NormalizeDouble(sl,digits); for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t>0 && PositionGetInteger(POSITION_MAGIC)==Magic && PositionGetString(POSITION_SYMBOL)==_Symbol){ MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r); r.action=TRADE_ACTION_SLTP; r.position=t; r.symbol=_Symbol; r.sl=sl; r.tp=0; if(!OrderSend(r,res)){ /* skip */ } } } }
    //+------------------------------------------------------------------+
    