//+------------------------------------------------------------------+
//|  GoldShark_BTCUSD.mq5                                             |
//|  Auto-generated by QMMP onboarding pipeline (#57/#61)            |
//|  Symbol: BTCUSD   Validated timeframe: H1                       |
//|  Entry: OsMA zero-cross + per-session floors                     |
//|  Exit : single basket trailing stop + early-only pyramiding      |
//|  DO NOT hand-edit — regenerate via scripts.qmmp.ea_generator     |
//+------------------------------------------------------------------+
#property copyright "QMMP"
#property version   "1.00"
#property strict

// ===== OPTIMISER-COMPATIBLE INPUTS (ranges in GoldShark_BTCUSD.set) =====
input int    OsMA_Fast = 12;
input int    OsMA_Slow = 26;
input int    OsMA_Signal = 9;
input double OsmaFloor_Asian = 17.97;
input double EmaAlign_Asian = 5.4;
input double BullsFloor_Asian = 131.15;
input double AtrFloor_Asian = 632.99;
input double OsmaFloor_London = 15.24;
input double EmaAlign_London = 10.26;
input double BullsFloor_London = 140.69;
input double AtrFloor_London = 567.04;
input double OsmaFloor_NewYork = 28.44;
input double EmaAlign_NewYork = 76.33;
input double BullsFloor_NewYork = 206.94;
input double AtrFloor_NewYork = 551.45;
input int    HardSL_pts = 628348;
input int    BE_pts = 11057;
input int    Trail_pts = 11057;
input int    Add_pts = 11057;
input double EarlyFrac = 0.15;
input int    MaxLegs = 4;
input double GBP_per_001 = 50.0;
input int    LotCapPerAccount = 100;

int      hMACD = INVALID_HANDLE, hATR = INVALID_HANDLE, hEMA = INVALID_HANDLE;
datetime lastBarTime = 0;

//+------------------------------------------------------------------+
int OnInit()
  {
   hMACD = iMACD(_Symbol, PERIOD_H1, OsMA_Fast, OsMA_Slow, OsMA_Signal, PRICE_CLOSE);
   hATR  = iATR(_Symbol, PERIOD_H1, 14);
   hEMA  = iMA(_Symbol, PERIOD_H1, 13, 0, MODE_EMA, PRICE_CLOSE);
   if(hMACD==INVALID_HANDLE || hATR==INVALID_HANDLE || hEMA==INVALID_HANDLE) return(INIT_FAILED);
   return(INIT_SUCCEEDED);
  }
void OnDeinit(const int reason){ IndicatorRelease(hMACD); IndicatorRelease(hATR); IndicatorRelease(hEMA); }

//--- OsMA[i] = MACD main - signal (MT5 iMACD buffer 0 = main = MACD line, buffer 1 = signal)
double OsMA(int shift)
  {
   double m[2], s[2];
   if(CopyBuffer(hMACD,0,shift,1,m)<1 || CopyBuffer(hMACD,1,shift,1,s)<1) return(0);
   return(m[0]-s[0]);
  }
double ATRv(int shift){ double a[1]; if(CopyBuffer(hATR,0,shift,1,a)<1) return(0); return(a[0]); }
double EMAv(int shift){ double e[1]; if(CopyBuffer(hEMA,0,shift,1,e)<1) return(0); return(e[0]); }

//--- session (broker/server time assumed ~UTC; adjust if your server offset differs)
string CurSession()
  {
   MqlDateTime dt; TimeToStruct(TimeCurrent(), dt); int h=dt.hour;
   if(h>=12 && h<21) return("NewYork");
   if(h>=7  && h<16) return("London");
   if(h>=0  && h<9 ) return("Asian");
   return("Off");
  }
void SessionFloors(string s, double &osma, double &ema, double &bulls, double &atr)
  {
   if(s=="Asian"){  osma=OsmaFloor_Asian;  ema=EmaAlign_Asian;  bulls=BullsFloor_Asian;  atr=AtrFloor_Asian; }
   else if(s=="London"){ osma=OsmaFloor_London; ema=EmaAlign_London; bulls=BullsFloor_London; atr=AtrFloor_London; }
   else { osma=OsmaFloor_NewYork; ema=EmaAlign_NewYork; bulls=BullsFloor_NewYork; atr=AtrFloor_NewYork; }
  }

//+------------------------------------------------------------------+
void OnTick()
  {
   // one decision per new bar
   datetime bt[]; if(CopyTime(_Symbol,PERIOD_H1,0,1,bt)<1) return;
   if(bt[0]==lastBarTime) { ManageBasket(); return; }
   lastBarTime = bt[0];
   ManageBasket();

   string sess = CurSession();
   if(sess=="Off") return;

   double o1=OsMA(1), o2=OsMA(2);                    // closed bars
   bool crossUp   = (o2<=0 && o1>0);
   bool crossDown = (o2>=0 && o1<0);
   if(!crossUp && !crossDown) return;

   double fOsma,fEma,fBulls,fAtr; SessionFloors(sess,fOsma,fEma,fBulls,fAtr);
   double osma_mag = MathAbs(o1);
   double ema_slope = EMAv(1)-EMAv(4);               // slope over 3 bars
   double ema_align = crossUp ? ema_slope : -ema_slope;
   double atr = ATRv(1)/_Point;
   // KEEP-floor gates (0 = OFF => always passes)
   if(fOsma>0 && osma_mag < fOsma) return;
   if(fEma!=0 && ema_align < fEma) return;
   if(fAtr>0 && atr < fAtr) return;
   // (bulls/bears power gates optional; add here if BullsFloor_* > 0)

   OpenLeg(crossUp);
  }

//--- money-management size: floor(equity/GBP_per_001) x 0.01 total, split across MaxLegs,
//--- margin- and 100-lot-capped. (Broker min lot / step assumed 0.01.)
double PerLegLots()
  {
   double eq = AccountInfoDouble(ACCOUNT_EQUITY);
   int units = (int)MathFloor(eq / GBP_per_001);
   double marginOne=0; OrderCalcMargin(ORDER_TYPE_BUY,_Symbol,0.01,SymbolInfoDouble(_Symbol,SYMBOL_ASK),marginOne);
   if(marginOne>0) units = (int)MathMin(units, MathFloor(eq/marginOne));
   units = (int)MathMin(units, LotCapPerAccount*100);   // 100 lots = 10000 x 0.01
   double perLeg = (units*0.01)/MaxLegs;
   double step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   perLeg = MathFloor(perLeg/step)*step;
   double vmin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   return(perLeg<vmin?0.0:perLeg);
  }

void OpenLeg(bool isLong)
  {
   double lots = PerLegLots(); if(lots<=0) return;
   double price = isLong?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = isLong? price-HardSL_pts*_Point : price+HardSL_pts*_Point;
   MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r);
   r.action=TRADE_ACTION_DEAL; r.symbol=_Symbol; r.volume=lots;
   r.type=isLong?ORDER_TYPE_BUY:ORDER_TYPE_SELL; r.price=price; r.sl=sl;
   r.deviation=50; r.magic=880011; r.comment="GoldShark_BTCUSD";
   OrderSend(r,res);
  }

//--- basket trailing stop (single stop behind best) + early pyramid add
double basketBest=0; bool armed=false; datetime cycleStart=0; int legCount=0; double lastLegPrice=0;
void ManageBasket()
  {
   if(PositionsTotalSym()==0){ armed=false; basketBest=0; legCount=0; return; }
   bool isLong = NetLong();
   double px = isLong?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK);
   if(basketBest==0) basketBest=px;
   basketBest = isLong?MathMax(basketBest,px):MathMin(basketBest,px);
   double avgEntry=AvgEntry();
   double profitPts = (isLong?(basketBest-avgEntry):(avgEntry-basketBest))/_Point * PositionsTotalSym();
   if(!armed && profitPts>=BE_pts) armed=true;
   if(armed)
     {
      double newSL = isLong? basketBest-Trail_pts*_Point : basketBest+Trail_pts*_Point;
      ModifyAllSL(newSL);
     }
   // early pyramid: add a leg if price advanced Add_pts beyond last leg and still early (heuristic: legCount<MaxLegs)
   if(legCount>0 && legCount<MaxLegs)
     {
      double adv=(isLong?(px-lastLegPrice):(lastLegPrice-px))/_Point;
      if(adv>=Add_pts){ OpenLeg(isLong); }
     }
  }
// --- helpers (position accounting for this symbol/magic) ---
int PositionsTotalSym(){ int c=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol) c++; } return(c); }
bool NetLong(){ double v=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol) v+=(PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?1:-1); } return(v>=0); }
double AvgEntry(){ double s=0; int n=0; for(int i=PositionsTotal()-1;i>=0;i--){ if(PositionGetTicket(i)>0 && PositionGetString(POSITION_SYMBOL)==_Symbol){ s+=PositionGetDouble(POSITION_PRICE_OPEN); n++; } } return(n>0?s/n:0); }
void ModifyAllSL(double sl){ for(int i=PositionsTotal()-1;i>=0;i--){ ulong t=PositionGetTicket(i); if(t>0 && PositionGetString(POSITION_SYMBOL)==_Symbol){ MqlTradeRequest r; MqlTradeResult res; ZeroMemory(r); r.action=TRADE_ACTION_SLTP; r.position=t; r.symbol=_Symbol; r.sl=sl; r.tp=0; OrderSend(r,res); } } }
//+------------------------------------------------------------------+
